theme = "congo"
baseURL = "https://www.joshmclark.com/"
defaultContentLanguage = "en"
enableRobotsTXT = true
uglyurls = true
paginate = '5'
summaryLength = '0'

[outputs]
home = ["HTML", "RSS", "JSON"]
