[[main]]
name = "development"
pageRef = "development"
weight = 10

[[main]]
name = "chocolate"
pageRef = "chocolate"
weight = 20

[[main]]
name = "spirits"
pageRef = "spirits"
weight = 30

# [[footer]]
# name = "Tags"
# pageRef = "tags"
# weight = 10
