colorScheme = "congo"
defaultAppearance = "dark"
autoSwitchAppearance = true
showAppearanceSwitcher = true
enableCodeCopy = true
mainSections = ["development", "chocolate", "spirits"]
robots = "all"
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = false
mainSections = ["development", "chocolate", "spirits"]

[article]
showDate = true
showDateUpdated = false
showAuthor = false
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
# editURL = "https://github.com/username/repo/"
editAppendPath = true
showHeadingAnchors = false
showPagination = true
invertPagination = true
showReadingTime = true
showTableOfContents = false
showTaxonomies = true
showWordCount = false
sharingLinks = ["facebook", "twitter", "reddit", "email"]

[list]
showBreadcrumbs = true
showSummary = false
groupByYear = false

[taxonomy]
showTermCount = false

[sitemap]
excludedKinds = ["taxonomy", "term"]
